services:
  server1:
    build:
      context: ..
      dockerfile: .docker/server/Dockerfile
    volumes:
      - dockermc:/mcserver
    environment:
      - MC_SERVER=server1
    image: dockermc-server
    networks:
      dockermc:
        aliases:
          - server1
    container_name: mc-server1
  server2:
    build:
      context: ..
      dockerfile: .docker/server/Dockerfile
    volumes:
      - dockermc:/mcserver
    environment:
      - MC_SERVER=server2
    image: dockermc-server
    networks:
      dockermc:
        aliases:
          - server2
    container_name: mc-server2
  bungee:
    build:
      context: ..
      dockerfile: .docker/bungee/Dockerfile
    image: bungee
    container_name: dockermc-bungee
    networks:
      dockermc:
        aliases:
          - bungee
    volumes:
      - dockermc:/mcserver
    ports:
      - 25565:25577
volumes:
  dockermc:
    name: dockermc
    external: true # Created by the outer Compose file
networks:
  dockermc:
    name: dockermc
    driver: bridge
