services:
  runner:
    build:
      context: ..
      dockerfile: .docker/runner/Dockerfile
      target: dev
      args:
        - DGID=${DGID}
    image: dockermc
    environment:
      - MC_VERSION=1.19
      - DGID=${DGID}
    volumes:
      - ../src:/src
      - dockermc:/mcserver
      - ./docker-compose.server.yml:/docker-compose.server.yml
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: dockermc-runner
volumes:
  dockermc:
    name: dockermc
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mcserver
